version: '3.8'

services:
  mysql_users:
    image: mysql:8.0
    container_name: mysql_users_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_USERS_DB_NAME}
      MYSQL_USER: ${MYSQL_USERS_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USERS_PASSWORD}
    volumes:
      - ./mysql/users:/var/lib/mysql  
    ports:
      - 3308:3306

  mysql_tasks:
    image: mysql:8.0
    container_name: mysql_tasks_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_TASKS_DB_NAME}
      MYSQL_USER: ${MYSQL_TASKS_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_TASKS_PASSWORD}
    volumes:
      - ./mysql/tasks:/var/lib/mysql  
    ports:
      - 3309:3306  
