version: '3.8'

services:
  mysql_users:
    image: mysql:8.0
    container_name: mysql_users_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_USERS_DB_NAME}
      MYSQL_USER: ${MYSQL_USERS_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USERS_PASSWORD}
    volumes:
      - ./mysql/users:/var/lib/mysql  
    ports:
      - 3308:3306

  mysql_tasks:
    image: mysql:8.0
    container_name: mysql_tasks_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_TASKS_DB_NAME}
      MYSQL_USER: ${MYSQL_TASKS_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_TASKS_PASSWORD}
    volumes:
      - ./mysql/tasks:/var/lib/mysql  
    ports:
      - 3309:3306  

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"